### ISSUE TITLE
Suggestions for docker-compose.yml

### ISSUE THREAD

**Issue by larsks** [pkhander/compose-prometheus#3]
In the configuration for the snmp exporter:

https://github.com/pkhander/compose-prometheus/blob/cf076f2518871eb65339aef65ba407baea31b3e7/docker-compose.yml#L25-L35

It's not necessary to use the `expose` directive. This is almost never necessary, and you're not using it on your other containers.

I don't think you need to publish UDP port 116, either. What service is using that port?

Lastly, I don't think you even need to publish tcp port 9116 for this container. It only needs to be reachable from the prometheus container, which since it is on the same network will be able to access the service regardless of whether or not it is published.

**Comment by pkhander** [comment]
While I was testing it, I would access the port to see if the exporter is actually working on scrapping.  You are right. No need to expose it any more as it is tested that prometheus container can access it directly.

I will test it by taking `expose` and `ports` out. If all works. I will submit a PR
